// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKHMWI1013CiaSMPVzhhFopXsboohvYww',
    appId: '1:592607300007:web:042208d33230f63b2f8e82',
    messagingSenderId: '592607300007',
    projectId: 'book-bloc',
    authDomain: 'book-bloc.firebaseapp.com',
    storageBucket: 'book-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvntXVSxcWTvISrliZxMcVbanFP6aEC0A',
    appId: '1:592607300007:android:6dd634482571b0ac2f8e82',
    messagingSenderId: '592607300007',
    projectId: 'book-bloc',
    storageBucket: 'book-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwBGO6KdhJlWq47kfIGWmsVPt6Vi_2Msk',
    appId: '1:592607300007:ios:170404ffce4fc85d2f8e82',
    messagingSenderId: '592607300007',
    projectId: 'book-bloc',
    storageBucket: 'book-bloc.appspot.com',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwBGO6KdhJlWq47kfIGWmsVPt6Vi_2Msk',
    appId: '1:592607300007:ios:170404ffce4fc85d2f8e82',
    messagingSenderId: '592607300007',
    projectId: 'book-bloc',
    storageBucket: 'book-bloc.appspot.com',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKHMWI1013CiaSMPVzhhFopXsboohvYww',
    appId: '1:592607300007:web:637f96e28e06e23f2f8e82',
    messagingSenderId: '592607300007',
    projectId: 'book-bloc',
    authDomain: 'book-bloc.firebaseapp.com',
    storageBucket: 'book-bloc.appspot.com',
  );
}
